# Generated by Django 4.2.20 on 2025-03-21 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_evento_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('evento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.evento')),
            ],
        ),
    ]
