# Generated by Django 4.2.20 on 2025-03-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='autonomo_foco',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='autonomo_pontuacao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='teleoperado_foco',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='teleoperado_pontuacao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
