# Generated by Django 4.2.20 on 2025-03-28 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_equipe_autonomo_foco_equipe_autonomo_pontuacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe', to='app.equipe')),
                ('evento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.evento')),
            ],
        ),
    ]
