# Generated by Django 4.2.20 on 2025-03-28 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_add_fields_to_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='autonomo_foco',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='autonomo_pontuacao',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='teleoperado_foco',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='teleoperado_pontuacao',
        ),
    ]
