# Generated by Django 4.2.20 on 2025-03-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_equipe_autonomo_foco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='evento',
        ),
        migrations.AddField(
            model_name='equipe',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='equipes'),
        ),
    ]
